### ISSUE TITLE
Munki hangs when caching Apple Softwareupdates

### ISSUE THREAD

**Issue by Lotusshaney** [munki/munki#1124]
When managedsoftwarecentre cli or GUI checks and downloads software updates from Apple it hangs at downloading.  This happens in both the CLI and GUI and appears to be the case if the update is already cached by the OS.

Cli run

```
`Checking Apple Software Update catalog...
    Caching CatalogURL https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
    Options: {'url': 'https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog', 'file': '/tmp/munki_swupd_cache/mirror/apple.sucatalog.download', 'follow_redirects': True, 'ignore_system_proxy': False, 'can_resume': True, 'additional_headers': {'User-Agent': 'managedsoftwareupdate/5.6.2.4398 Darwin/21.1.0 (x86_64) (MacBookPro13,3)'}, 'download_only_if_changed': False, 'cache_data': None, 'logging_function': <function display_debug2 at 0x104cbb1f0>, 'pkginfo': None}
    URLSession_task_didReceiveChallenge_completionHandler_
    Authentication challenge for Host: swscan.apple.com Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
    Allowing OS to handle authentication request
	0..20..40..60..80..100
    Status: 200
    Headers: {'Content-Type': 'application/x-apple-plist', 'x-icloud-versionid': 'c9eabdd0-5d3f-11ec-9de7-248a078d440a', 'X-Apple-Request-UUID': '3ad263dd-a2d4-4a40-a128-e5202395bf86, 3ad263dd-a2d4-4a40-a128-e5202395bf86', 'Server': 'ATS/9.0.3', 'X-iCloud-Content-Length': '6870751', 'CDNUUID': '8fad7f73-9e0f-4b0c-b574-2d2d0a7f319d-127520717', 'X-iCLoud-Availability': '[R, B, PL]', 'Cache-Control': 'max-age=84', 'Date': 'Thu, 16 Dec 2021 11:17:04 GMT', 'Content-Length': '6870751', 'X-Responding-Server': 'massilia_protocol_028:328004902:mr33p01if-zteh08093901.mr.if.apple.com:8081:21S125:68ca597b9c33', 'X-Apple-MS-Content-Length': '6870751', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Connection': 'keep-alive', 'Accept-Ranges': 'bytes', 'Etag': '"1FC3D656BB13C298507AEDE5856842AB"', 'Last-Modified': 'Wed, 15 Dec 2021 00:41:49 GMT'}
Checking for available Apple Software Updates...
    softwareupdate cmd: ['/usr/local/munki/ptyexec', '/usr/sbin/softwareupdate', '--verbose', '-d', '-a']
    Finding available software...
    Downloading macOS Monterey 12.1...`
```

and it just hangs forever Downloading macOS Monterey 12.1...

The GUI hangs at the same Downloading macOS Monterey 12.1...

If software update is run from command line this is the output

`softwareupdate-da
Software Update Tool
Finding available software
Downloading macOS Monterey 12.1
Downloaded: macOS Monterev 12.1` 

and it exits.

Running softwareupdate via ptyexec also exits

```
sudo /usr/local/munki/ptyexec /usr/sbin/softwareupdate --verbose -d -a
Software Update Tool

Finding available software
Downloading macOS Monterey 12.1

Downloaded: macOS Monterey 12.1
```

My guess is that no progress of the download in the output results in managedsoftwarecentre hanging.

Happens on macOS 10.15.x, 11.6.x and 12.x
managedsoftwarecentre version 5.6.2.4398

**Comment by gregneagle** [comment]
This happens only while downloading macOS 12.1 specifically?  Certainly have not seen this for other OS versions in my environment. Not sure about 12.1

**Comment by Lotusshaney** [comment]
No its happened alot. 10.15.6-10.15.7 I had hundreds of them sticking, 11.6.0-11.6.1 and now 12.0.1-12.1 are also having the same problem

**Comment by Lotusshaney** [comment]
I have spoken ok Slack but nothing yet

**Comment by ofirgalcon** [comment]
Same problem here.

**Comment by gregneagle** [comment]
I’d also like to point out that on Apple silicon, Munki doesn’t attempt to download Apple updates at all

**Comment by gregneagle** [comment]
If you two don’t have any more detail, and I have no way to reproduce or observe the issue, it’s unlikely I’ll be able to address it.

**Comment by ofirgalcon** [comment]
What details would you like? I have a computer with this problem right here

**Comment by Lotusshaney** [comment]
What details would you like ?

**Comment by Lotusshaney** [comment]
Greg this is on Intel Macs so far.  Maybe have the same behaviour as M1's and defer updates to the PrefPane ?

**Comment by gregneagle** [comment]
On Slack you said you saw this on M1 as well. So lots of data yet to collect, and double-checking of that data.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/700560/146407359-ef60070b-b6a9-480c-a8a0-51b76eb785d1.png">

I don't think this is a widespread problem, or I would have heard about it earlier. So there must be a specific trigger in your environment that is not present in mine.

**Comment by ofirgalcon** [comment]
When I run with -vvv I see this, no idea if it's relevant

`Checking for available Apple Software Updates...
    softwareupdate cmd: ['/usr/local/munki/ptyexec', '/usr/sbin/softwareupdate', '--verbose', '-d', '-a']
    Finding available software...
    2021-12-16 15:59:33.318 softwareupdate[56606:5546774] XType: com.apple.fonts is not accessible.
    2021-12-16 15:59:33.319 softwareupdate[56606:5546774] XType: XTFontStaticRegistry is enabled.
    Downloading macOS Monterey 12.1...`

**Comment by gregneagle** [comment]
`softwareupdate` itself logs to `/var/log/install.log`

**Comment by Lotusshaney** [comment]
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: Starting softwareupdate CLI tool
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=6155, uid=0, installAuth=NO rights=(), transactions=0 (/usr/sbin/softwareupdate)
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: Controller: Time interval since last scan - 84.718941
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=6155, uid=0, installAuth=NO rights=(), transactions=0 (/usr/sbin/softwareupdate)
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: Controller: currentPallasAudience - (null), shouldScan - 1, productKeysInActiveForegroundTransactions - 0, client = 3, shouldScanForClient: 1, foregroundScan: 0
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: SUOSUShimController: Start legacy scan
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: Query for available updates: FINISHED
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: SUOSUShimController: Start MSU scan
2021-12-16 16:24:28+00 Beauty softwareupdate[6155]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: Repeated Cmd-R scans in close proximity: clearing catalog metadata cache
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: SUOSUServiceDaemon: Adding client: (null) (pid = 6155, uid = 0, path = /usr/sbin/softwareupdate, connection remote object interface = <NSXPCInterface: 0x7fc0056cce00>, exported interface = <NSXPCInterface: 0x7fc00569e980>, remote object proxy = <__NSXPCInterfaceProxy_SUOSUServiceClientProtocol: 0x7fc00567f9d0>)
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: SUOSUMobileSoftwareUpdateController: Set bridgeOS catalog override to catalogURL default
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=6155, uid=0, installAuth=NO rights=(), transactions=0 (/usr/sbin/softwareupdate)
2021-12-16 16:24:28+00 Beauty system_installd[823]: PackageKit: Adding client PKInstallDaemonClient pid=340, uid=200 (/System/Library/CoreServices/Software Update.app/Contents/Resources/softwareupdated)
2021-12-16 16:24:28+00 Beauty softwareupdated[340]: SUScan: Scan for client pid 340 (/System/Library/CoreServices/Software Update.app/Contents/Resources/softwareupdated)
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Got status 200
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: SUScan: Using catalog https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Take com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion with type BackgroundTask for pid 781, id 0x8BDB
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:29+00 Beauty softwareupdate[6155]: SUOSUShimController: Available MSU updates: (
	    "<SUOSUProduct: MSU_UPDATE_21C52_patch_12.1>"
	)
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion for pid 781, id 0x8BDB
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Could not cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion - no assertion found for pid 781
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:29+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:29+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:30+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:30+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:31+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: JS: No bundle at/Applications/SafeView.app
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: JS: 12.0.1
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:32+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:33+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:33+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:33+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:33+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:33+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:33+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: bridgeOS: Minimum bridge version requirement satisfied ((null)), skipping search for bridgeOS update
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:35+00 Beauty softwareupdated[340]: Failed to get bridge device
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SUScan: Elapsed scan time = 7.7
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Take com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion with type BackgroundTask for pid 781, id 0x8BDC
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Refreshing available updates from scan
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SUStatisticsManager: Successfully reported statistics for category 5
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion for pid 781, id 0x8BDC
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Scan (f=1, d=0) completed 
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: 0 updates found:
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Could not cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion - no assertion found for pid 781
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Could not cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion - no assertion found for pid 781
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:36+00 Beauty softwareupdate[6155]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SUOSUServiceDaemon: Adding client: (null) (pid = 6155, uid = 0, path = /usr/sbin/softwareupdate, connection remote object interface = <NSXPCInterface: 0x7fc00a248fd0>, exported interface = <NSXPCInterface: 0x7fc00991f690>, remote object proxy = <__NSXPCInterfaceProxy_SUOSUServiceClientProtocol: 0x7fc00a2e88c0>)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SUOSUMobileSoftwareUpdateController: Set bridgeOS catalog override to catalogURL default
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: MSU updates found: (
	    "<SUOSUProduct: MSU_UPDATE_21C52_patch_12.1>"
	)
2021-12-16 16:24:36+00 Beauty softwareupdate[6155]: External updates: (
	)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: MSU updates found: (
	    "<SUOSUProduct: MSU_UPDATE_21C52_patch_12.1>"
	)
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: External updates: (
	)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: MSU updates found: (
	    "<SUOSUProduct: MSU_UPDATE_21C52_patch_12.1>"
	)
2021-12-16 16:24:36+00 Beauty softwareupdate[6155]: Controller: Received availableUpdatesChanged notification; new updates: [MSU_UPDATE_21C52_patch_12.1]; new major updates: [002-42435, 002-23774, 002-42341, 002-23589, 071-97382, 071-78704, 001-68446, 001-51042, 001-36801, 061-26589, 041-91758]
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: Controller: Received availableUpdatesChanged notification; new updates: [MSU_UPDATE_21C52_patch_12.1]; new major updates: [002-42435, 002-23774, 002-42341, 002-23589, 071-97382, 071-78704, 001-68446, 001-51042, 001-36801, 061-26589, 041-91758]
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:36+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUShimController: Armed: 0, with mode: 0, date: (null), updates queued for later: (
	)
2021-12-16 16:24:36+00 Beauty softwareupdate[6155]: SUOSUShimController: Armed: 0, with mode: 0, date: (null), updates queued for later: (
	)
2021-12-16 16:24:36+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Take com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion with type BackgroundTask for pid 781, id 0x8BDF
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: CLI scan returned: (
	    "<SUOSUProduct: MSU_UPDATE_21C52_patch_12.1>"
	)
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: Disk already has enough free space for updates (required: 11772361863, available: 35356508160)
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion for pid 781, id 0x8BDF
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: SUOSUAuthenticationManager: Disabling local authentication requirement
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: Adding client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: SoftwareUpdate: request for status for unknown product MSU_UPDATE_21C52_patch_12.1
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: AssertionMgr: Could not cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion - no assertion found for pid 781
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:37+00 Beauty SoftwareUpdateNotificationManager[781]: (null)：softwareupdated: Service connection invalidated!
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: Removing client SUUpdateServiceClient pid=781, uid=501, installAuth=NO rights=(), transactions=0 (/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager)
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: SUOSUAuthorizationController: Non-interactive authorization succeeded for non-admin user
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: Sending authorization to notification service
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: SUOSUNotificationManagerController: Connection to notification manager service invalidated
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: SUOSUNotificationManagerController: Error connecting to notification manager service to set authorization: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.SoftwareUpdateNotificationManagerService was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.SoftwareUpdateNotificationManagerService was invalidated: failed at lookup with error 3 - No such process.}
2021-12-16 16:24:37+00 Beauty softwareupdate[6155]: SUOSUNotificationManagerController: Failed to authorize???
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: No matching products found while calculating disk space required
2021-12-16 16:24:37+00 Beauty softwareupdated[340]: No keys matching () available for download

**Comment by Lotusshaney** [comment]
That was while running Mangedsoftwarecentre GUI

**Comment by Lotusshaney** [comment]
> On Slack you said you saw this on M1 as well. So lots of data yet to collect, and double-checking of that data. <img alt="image" width="379" src="https://user-images.githubusercontent.com/700560/146407359-ef60070b-b6a9-480c-a8a0-51b76eb785d1.png">
> 
> I don't think this is a widespread problem, or I would have heard about it earlier. So there must be a specific trigger in your environment that is not present in mine.

Sorry that was a typo. Not on M1 only Intel so far. My environment is mainly Intel with a few M1’s

**Comment by OvrAp3x** [comment]
I am seeing the same behaviour as OP, 
This is on intel mac's, I have just recently enabled the Preference
`defaults write /Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates -bool True`
But have been struggeling better part of a day to figure out what is going on here.

**Comment by Lotusshaney** [comment]
Is there any more information, logs, etc you require ?

**Comment by gregneagle** [comment]
I certainly don’t have enough information to guess what might be happening for you, or to reproduce the issue, so there’s not much I can do at this point.

**Comment by ofirgalcon** [comment]
Can you think of any tests or logs we could provide to help. This is definitely an issue that I've been noticing for a while. Could it be related to Apple's software update also downloading the file?

**Comment by gregneagle** [comment]
Munki _calls_ Apple’s software update to download the file…

**Comment by OvrAp3x** [comment]
I know that for other updates it prints a list of updates and says like*needs reboot* etc. This update does not print that in the message, maybe the flag is missing causing it to be misinterperted or something?
*Speculation*

**Comment by stephanvanhienen** [comment]
I'm having the same issue on multiple clients.
Not sure how I can give more information -vvv gives the following ;

Checking Apple Software Update catalog...
    Caching CatalogURL https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
    Options: {'url': 'https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog', 'file': '/tmp/munki_swupd_cache/mirror/apple.sucatalog.download', 'follow_redirects': True, 'ignore_system_proxy': False, 'can_resume': True, 'additional_headers': {'User-Agent': 'managedsoftwareupdate/5.6.2.4398 Darwin/21.1.0 (x86_64) (MacBookPro11,4)'}, 'download_only_if_changed': False, 'cache_data': None, 'logging_function': <function display_debug2 at 0x106db13a0>, 'pkginfo': None}
    URLSession_task_didReceiveChallenge_completionHandler_
    Authentication challenge for Host: swscan.apple.com Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
    Allowing OS to handle authentication request
        0..20..40..60..80..100
    Status: 200
    Headers: {'Content-Type': 'application/x-apple-plist', 'x-icloud-versionid': '7dd4c4c0-62c8-11ec-9aac-248a078d598e', 'X-Apple-Request-UUID': '851d10c9-e085-4eff-9aae-996f0b5b8201, 851d10c9-e085-4eff-9aae-996f0b5b8201', 'Server': 'ATS/9.0.3', 'X-iCloud-Content-Length': '6870751', 'CDNUUID': 'f33fc1cc-d1df-4eda-b1d3-40382095659b-363928554', 'X-iCLoud-Availability': '[B, PL, R]', 'Cache-Control': 'max-age=520', 'Date': 'Mon, 27 Dec 2021 09:16:25 GMT', 'Content-Length': '6870751', 'X-Responding-Server': 'massilia_protocol_028:428008504:pv49p01if-zteh17133901.pv.if.apple.com:8083:21T149:5c0afdc2c4a8', 'X-Apple-MS-Content-Length': '6870751', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Connection': 'keep-alive', 'Accept-Ranges': 'bytes', 'Etag': '"B30A6AEF308DC42989143CE0EB616102"', 'Last-Modified': 'Wed, 22 Dec 2021 01:42:58 GMT'}
Checking for available Apple Software Updates...
    softwareupdate cmd: ['/usr/local/munki/ptyexec', '/usr/sbin/softwareupdate', '--verbose', '-d', '-a']
    Finding available software...
    2021-12-27 10:16:30.262 softwareupdate[2210:26961] XType: com.apple.fonts is not accessible.
    2021-12-27 10:16:30.262 softwareupdate[2210:26961] XType: XTFontStaticRegistry is enabled.
    Downloading macOS Monterey 12.1...

And then nothing.

**Comment by stephanvanhienen** [comment]
I also have a client hanging on the 'Finding available software...' ;

Checking Apple Software Update catalog...
    Caching CatalogURL https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
    Options: {'url': 'https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog', 'file': '/tmp/munki_swupd_cache/mirror/apple.sucatalog.download', 'follow_redirects': True, 'ignore_system_proxy': False, 'can_resume': True, 'additional_headers': {'User-Agent': 'managedsoftwareupdate/5.6.2.4398 Darwin/21.1.0 (x86_64) (MacBookPro15,1)'}, 'download_only_if_changed': False, 'cache_data': None, 'logging_function': <function display_debug2 at 0x1060b2310>, 'pkginfo': None}
    URLSession_task_didReceiveChallenge_completionHandler_
    Authentication challenge for Host: swscan.apple.com Realm: None AuthMethod: NSURLAuthenticationMethodServerTrust
    Allowing OS to handle authentication request
        0..20..40..60..80..100
    Status: 200
    Headers: {'Content-Type': 'application/x-apple-plist', 'x-icloud-versionid': '7dd4c4c0-62c8-11ec-9aac-248a078d598e', 'X-Apple-Request-UUID': '851d10c9-e085-4eff-9aae-996f0b5b8201, 851d10c9-e085-4eff-9aae-996f0b5b8201', 'Server': 'ATS/9.0.3', 'X-iCloud-Content-Length': '6870751', 'CDNUUID': '970d737a-a222-437b-b82f-1b60a09cbb47-11625391', 'X-iCLoud-Availability': '[B, PL, R]', 'Cache-Control': 'max-age=304', 'Date': 'Mon, 27 Dec 2021 09:36:49 GMT', 'Content-Length': '6870751', 'X-Responding-Server': 'massilia_protocol_028:428008504:pv49p01if-zteh17133901.pv.if.apple.com:8083:21T149:5c0afdc2c4a8', 'X-Apple-MS-Content-Length': '6870751', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Connection': 'keep-alive', 'Accept-Ranges': 'bytes', 'Etag': '"B30A6AEF308DC42989143CE0EB616102"', 'Last-Modified': 'Wed, 22 Dec 2021 01:42:58 GMT'}
Checking for available Apple Software Updates...
    softwareupdate cmd: ['/usr/local/munki/ptyexec', '/usr/sbin/softwareupdate', '--verbose', '-d', '-a']
    Finding available software...

**Comment by stephanvanhienen** [comment]
And there should also be a timeout when running the softwareupdate command, now managedsoftwareupdate just hangs. (my test run is still running after 4 hours)

**Comment by ofirgalcon** [comment]
Same here. Hangs for many hours until the user presses Cancel.

**Comment by stephanvanhienen** [comment]
Any news on this issue ?
Let me know if I should provide more information.

**Comment by OvrAp3x** [comment]
> Since there has been no solution, I have deployed the update as a script instead.
> 
> Hopefully it is fixed before 12.2 the next update😅

Below is the script used, deployed as apackage with a condition to only install on mac where os version is less than 12.1

Hope this helps somebody
>```
FILE=/Applications/Install\ macOS\ Monterey.app if [ ! -d "$FILE" ];then echo "monterey downloader not detected" /usr/sbin/softwareupdate --fetch-full-installer --full-installer-version 12.1 fi if [ -d "$FILE" ];then echo "monterey downloader detected" '/Applications/Install macOS Monterey.app/Contents/Resources/startosinstall' --agreetolicense --forcequitapps fi 
```

**Comment by gregneagle** [comment]
Again: not seeing the reported behavior here and have no way to reproduce it. If I can't see it or can't reproduce it I have no hope of addressing it.

The fact that only _some_ sites/orgs/companies are seeing this makes me suspect there is another piece of software involved; perhaps some security software or the like that is causing `softwareupdate` to never exit...

**Comment by gregneagle** [comment]
it might be instructive for an admin at a site experiencing this issue to do these tests:

1) Build a new test machine with macOS 12.0 or 12.0.1, the munki tools, and _nothing else_ (make sure the manifest has no items at all, or configure `AppleSoftwareUpdatesOnly` to true)
2) Use `managedsoftwareupdate` to check for and download Apple updates

If this is successful, it's more evidence that some other bit of installed software is involved. If it's not successful:

3) Take the machine to a different network (for example, take a laptop home) and try it there. 

If that's successful, then something on your organization's network might be causing this issue.

If any of you experiencing this have already tried these things, please post your results.

**Comment by gregneagle** [comment]
"there should also be a timeout when running the softwareupdate command" there is; it's just much longer than you might like. What is the appropriate timeout length when downloading many gigabytes over what might be a slow internet connection? A successful download could take hours.

**Comment by ofirgalcon** [comment]
All the computers I see this on are also managed via MDM. I have not tested without.

**Comment by gregneagle** [comment]
All of my computers are also managed via MDM.

**Comment by Lotusshaney** [comment]
Hi Greg,

My tests have been with a vanilla  OS restored from Apple, Then Munki manually installed and configured with defaults write commands.

I have tried on several networks.  Corporate, home and tethered to a mobile and it makes no difference.

As I also noted in the original post, if I manually run softwareupdate from CLI or from /usr/local/munki/ptyexec the softwareupdate command actually works and downloads the update.  This happens on any of the networks I have tried so rules out the theory that something on the network is blocking the download.

As for MDM I have tried enrolling the Mac into MDM and it makes no difference.

**Comment by patgmac** [comment]
I am seeing the same issue. I've tried with and without MDM, reinstalled OS, and tried without middleware. 

> "there should also be a timeout when running the softwareupdate command" there is; it's just much longer than you might like. What is the appropriate timeout length when downloading many gigabytes over what might be a slow internet connection? A successful download could take hours.

How long is it? I left it all weekend and it was still hung. I'm on gigabit Fiber so it shouldn't be a speed issue. I can download within System Preferences within a few minutes. Once hung, I stop seeing any activity in Install.log.

**Comment by vmiller** [comment]
I realized I am seeing this issue as well, so I set out to do some testing and gather some information.

The test : 

This was done on my home network
Install 12.0.1 via USB drive on an iMac16,2 (late 2015)
Download and install munkitools_DEP-5.6.2.4398.pkg
sudo defaults write /Library/Preferences/ManagedInstalls.plist InstallSoftwareUpdates -bool True

Open Managed Software Center and check for updates.

Let run overnight.  Capture logs in the morning.  When I unlocked the machine in the morning Managed Software Center displayed an error.  A traceback is in the munki log.

Jan 20 2022 07:23:34 -0500 Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 980, in main
    appleupdates.appleSoftwareUpdatesAvailable(
  File "/usr/local/munki/munkilib/appleupdates/core.py", line 73, in appleSoftwareUpdatesAvailable
    return appleUpdatesObject.software_updates_available(
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 824, in software_updates_available
    updatecount = self.check_for_software_updates(force_check=True)
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 324, in check_for_software_updates
    if self.download_available_updates():  # Success; ready to install.
  File "/usr/local/munki/munkilib/appleupdates/au.py", line 169, in download_available_updates
    results = su_tool.run(
  File "/usr/local/munki/munkilib/appleupdates/su_tool.py", line 223, in run
    time.sleep(1)
  File "/usr/local/munki/managedsoftwareupdate", line 88, in signal_handler
    sys.exit()
SystemExit



I copied the munki log and install.log to gists :  

ManagedSoftwareUpdate.log : https://gist.github.com/vmiller/7f3888c6efa25510bf8264a3fd855911
/var/log/install.log : https://gist.github.com/vmiller/40eb7e1e857920c42508ee6bf4e07f18

**Comment by vmiller** [comment]
The SystemExit may correspond to when I exited out of MSC.  I'll admit to being a bit lost trying to comb through install.log for clues.

I'm going to continue testing to see if I can consistently duplicate the issue.

**Comment by poundbangbash** [comment]
I just killed the hung `managedsoftwareupdate` process that had been running since yesterday and re-ran it.
The softwareupdate phase hung again and in the /var/log/install.log I see the `No keys matching () available for download` again.

![image](https://user-images.githubusercontent.com/1416288/150390106-f847fb82-7651-4db5-a9d3-3021ac990973.png)

**Comment by gregneagle** [comment]
"SystemExit means the process was stopped by the system (restart, force quit, etc.). "

This is likely /usr/local/munki/supervisor killing the managedsoftwareupdate run after 43200 seconds, or 12 hours.

**Comment by vmiller** [comment]
"This is likely /usr/local/munki/supervisor killing the managedsoftwareupdate run after 43200 seconds, or 12 hours."

12 hours lines up with my testing timeline.

**Comment by gregneagle** [comment]
"I just killed the hung managedsoftwareupdate process that had been running since yesterday and re-ran it.
The softwareupdate phase hung again and in the /var/log/install.log I see the No keys matching () available for download again."

Just reminding everyone that what is happening here is `/usr/sbin/softwareupdate` is hanging/spinning/failing to exit, and `managedsoftwareupdate` is waiting for it to exit, before being killed after running 12 hours.

The task at hand is identifying _why_ `/usr/sbin/softwareupdate` is failing to exit. And again: for whatever reason, not seeing that behavior here.

**Comment by poundbangbash** [comment]
Right. Thanks for the re-focus on the main issue of softwareupdate, Greg.

With this machine I have in the hanging state, running `sudo softwareupdate -da` results in the same hang at `Downloading macOS Monterey 12.1`.  So, time to go spelunking around that native process. I have some security agents I can start stripping out and see if that affects the results.

**Comment by Lotusshaney** [comment]
Not what I’m seeing. The process only hangs when spawned from MSC. 

If softwareupdate is run from terminal it works without a problem

**Comment by poundbangbash** [comment]
Well this is interesting.

I restarted the computer in the attempt to wipe and start from scratch with a bare consumer OS instead of our company build. When all apps quit and the loginwindow would normally be shown, the apple logo with a progress bar at about 1/3 complete appeared for 4-8 seconds.

Upon that disappearing the computer rebooted, and the apple logo/progress bar flashed a few times like it was doing an update.  At one point the progress bar moved much slower than a normal boot, and showed no status update of minutes remaining as if it were doing the actual update. During the boot sequence, the Apple logo disappeared and reappeared 6x - one finally showing a status of 10 minutes remaining.

When it booted up finally, the OS is 12.1. It has updated.

So without doing anything besides rebooting the computer - no notification the update was ready, no confirming to apply the update, no prompt to restart from any app/UI, the OS update applied on reboot.  

Clearly the OS update was prepped/triggered already and In this prepped update state the softwareupdate process hangs when checking for updates. Gosh what a mess.

For those that are seeing the update process hang in MSC, have you tried rebooting to see if the OS update applies?
Anyone know how to determine if an OS update is prepped for running on next reboot?  It doesn't appear the logs are showing that unless I completely missed it.

**Comment by poundbangbash** [comment]
Digging in the `install.log` again, I see at 12:52:38, a timestamp that doesn't match any other actions that I can tell, the installer started stashing itself to "Registering products for post-logout install".


```
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: AssertionMgr: Take com.apple.SoftwareUpdate.BeforePostlogout assertion with type PreventUserIdleSystemSleep for pid 5237, id 0x83BF
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: SUOSUUpdateController: Registering products for post-logout install (now is later = 0, restarting now = 0, is InstallAssistant: 0 ): [(
	    "MSU_UPDATE_21C52_patch_12.1"
	)] [(
	    "[>>>\n                     humanReadableUpdateName: macOS Monterey 12.1\n                               uniqueBuildID: (null)\n                          originalUpdateType: Minor\n                                  updateUUID: 6B727B19-9E33-4103-B579-B253B81F26C7\n                              productVersion: 12.1\n                         productBuildVersion: 21C52\n                           productSystemName: macOS\n                                 releaseType: (null)\n                                   publisher: Apple Inc.\n                                 releaseDate: 2021-12-13 00:00:00 +0000\n                              restoreVersion: 21.3.52.0.0,0\n                   targetUpdateBridgeVersion: (null)\n                      targetUpdateSFRVersion: (null)\n                           prerequisiteBuild: 21A559\n                       prerequisiteOSVersion: 12.0.1\n                            supportedDevices: (null)\n                             fullReplacement: NO\n                                downloadSize: 2359446672\n                              unarchivedSize: 2989865984\n                              msuPrepareSize: 7819903111\n                             preparationSize: 10809769095\n                            installationSize: 962592768\n                  minimumSystemPartitionSize: 16638803968\n                      totalRequiredFreeSpace: 11772361863\n                         streamingZipCapable: YES\n                      systemPartitionPadding: {\n    1024 = 1280;\n    128 = 1280;\n    16 = 160;\n    256 = 1280;\n    32 = 320;\n    512 = 1280;\n    64 = 640;\n    768 = 1280;\n    8 = 80;\n}\n           autoDownloadAllowableOverCellular: NO\n               downloadAllowableOverCellular: NO\n                                downloadable: NO\n                    disableSiriVoiceDeletion: NO\n                             disableCDLevel4: NO\n                          disableAppDemotion: NO\n                       disableInstallTonight: NO\n                                 rampEnabled: NO\n                            mdmDelayInterval: 0\n                           autoUpdateEnabled: NO\n                     mandatoryUpdateEligible: NO\n                   mandatoryUpdateVersionMin: (null)\n                   mandatoryUpdateVersionMax: (null)\n                     mandatoryUpdateOptional: NO\n      mandatoryUpdateRestrictedToOutOfTheBox: NO\n                              criticalUpdate: NO\n                                 productType: (null)\n                            autoInstallDelay: 0\n                                 notifyAfter: NO\n                                   sepDigest: (null)\n                               sepTBMDigests: (null)\n                                  rsepDigest: (null)\n                              rsepTBMDigests: (null)\n            documentationReleaseNotesSummary: {length = 4872, bytes = 0x3c21444f 43545950 45206874 6d6c2050 ... 3c2f6874 6d6c3e0a }\n                   documentationReleaseNotes: (null)\n               documentationLicenseAgreement: (null)\n documentationHumanReadableDocumentationName: macOS Monterey 12.1\n                     documentationSLAVersion: 1775\n                       documentationLanguage: en-US\n                                sfrAssetType: (null)\n                           sfrProductVersion: (null)\n                      sfrProductBuildVersion: (null)\n                              sfrReleaseType: (null)\n                           sfrRestoreVersion: (null)\n                        sfrPrerequisiteBuild: (null)\n                      sfrPrerequisiteVersion: (null)\n                          sfrFullReplacement: NO\n                         sfrSupportedDevices: (null)\n                             sfrDownloadSize: 0\n                           sfrUnarchivedSize: 0\n                           sfrMSUPrepareSize: 0\n                          sfrPreparationSize: 0\n                         sfrInstallationSize: 0\n               sfrMinimumSystemPartitionSize: 0\n                   sfrTotalRequiredFreeSpace: 0\n                        updateBrainAssetType: com.apple.MobileAsset.MobileSoftwareUpdate.MacUpdateBrain\n             updateBrainCompatibilityVersion: 20\n                     updateBrainBuildVersion: 21C52\n                        associatedDescriptor: macOS Monterey 12.1 21C52 (Customer)\n                        primarySFRDescriptor: (null)\n                      secondarySFRDescriptor: (null)\n                       updateBrainDescriptor: iOS 12.1 21C52 (Customer)\n                 shouldPerformBridgeOSUpdate: NO\n                    bridgeOSVersionToInstall: (null)\n                   bridgeOSDownloadSizeBytes: (null)\n                   bridgeOSDownloadDirectory: (null)\n                  shouldPerformRosettaUpdate: NO\n                     rosettaVersionToInstall: (null)\n                    rosettaPackageSpecifiers: (null)\n                      recoveryOSUpdateResult: NO\n                    recoveryOSUpdateRequired: NO\n                       recoveryOSUpdateError: (null)\n                  recoveryOSUpdateAttributes: (null)\n<<<]"
	)]
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: SUOSUAuthorizationController: Non-interactive authorization succeeded for non-admin user
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: SUOSUUpdateController: Sending authorization to softwareupdated
2022-01-19 12:52:38-06 SNSNSNSNSNSN system_installd[1306]: PackageKit: Adding client PKInstallDaemonClient pid=299, uid=200 (/System/Library/CoreServices/Software Update.app/Contents/Resources/softwareupdated)
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: SUOSUUpdateController: Successfully authorized with softwareupdated
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: SUOSUUpdateController: User Side Stashing succeeded
2022-01-19 12:52:38-06 SNSNSNSNSNSN softwareupdated[299]: Stashing...
2022-01-19 12:52:38-06 SNSNSNSNSNSN softwareupdated[299]: authorizeWithEmptyAuthorizationForRights: Requesting provided rights: 18
2022-01-19 12:52:38-06 SNSNSNSNSNSN softwareupdated[299]: SUHelperProxy: stash login
2022-01-19 12:52:38-06 SNSNSNSNSNSN suhelperd[326]: SUHelperD: stash login
2022-01-19 12:52:38-06 SNSNSNSNSNSN suhelperd[326]: GetModel: model = Macmini; major rev = 8; minor rev = 1
2022-01-19 12:52:38-06 SNSNSNSNSNSN suhelperd[326]: Machine appears to be AR capable
2022-01-19 12:52:38-06 SNSNSNSNSNSN suhelperd[326]: VEK state: user:1, sys:1
2022-01-19 12:52:38-06 SNSNSNSNSNSN suhelperd[326]: User stash for nil will attempt fall back.
2022-01-19 12:52:38-06 SNSNSNSNSNSN suhelperd[326]: Staged principal user cookie to /private/var/db
2022-01-19 12:52:38-06 SNSNSNSNSNSN SoftwareUpdateNotificationManager[5237]: SUOSUUpdateController: Registered product keys for post-logout install: [MSU_UPDATE_21C52_patch_12.1]
2022-01-19 12:52:38-06 SNSNSNSNSNSN softwareupdated[299]: SUOSUServiceDaemon: Queued descriptor up for postlogout apply: (
	    "[>>>\n                     humanReadableUpdateName: macOS Monterey 12.1\n                               uniqueBuildID: (null)\n                          originalUpdateType: Minor\n                                  updateUUID: 6B727B19-9E33-4103-B579-B253B81F26C7\n                              productVersion: 12.1\n                         productBuildVersion: 21C52\n                           productSystemName: macOS\n                                 releaseType: (null)\n                                   publisher: Apple Inc.\n                                 releaseDate: 2021-12-13 00:00:00 +0000\n                              restoreVersion: 21.3.52.0.0,0\n                   targetUpdateBridgeVersion: (null)\n                      targetUpdateSFRVersion: (null)\n                           prerequisiteBuild: 21A559\n                       prerequisiteOSVersion: 12.0.1\n                            supportedDevices: (null)\n                             fullReplacement: NO\n                                downloadSize: 2359446672\n                              unarchivedSize: 2989865984\n                              msuPrepareSize: 7819903111\n                             preparationSize: 10809769095\n                            installationSize: 962592768\n                  minimumSystemPartitionSize: 16638803968\n                      totalRequiredFreeSpace: 11772361863\n                         streamingZipCapable: YES\n                      systemPartitionPadding: {\n    1024 = 1280;\n    128 = 1280;\n    16 = 160;\n    256 = 1280;\n    32 = 320;\n    512 = 1280;\n    64 = 640;\n    768 = 1280;\n    8 = 80;\n}\n           autoDownloadAllowableOverCellular: NO\n               downloadAllowableOverCellular: NO\n                                downloadable: NO\n                    disableSiriVoiceDeletion: NO\n                             disableCDLevel4: NO\n                          disableAppDemotion: NO\n                       disableInstallTonight: NO\n                                 rampEnabled: NO\n                            mdmDelayInterval: 0\n                           autoUpdateEnabled: NO\n                     mandatoryUpdateEligible: NO\n                   mandatoryUpdateVersionMin: (null)\n                   mandatoryUpdateVersionMax: (null)\n                     mandatoryUpdateOptional: NO\n      mandatoryUpdateRestrictedToOutOfTheBox: NO\n                              criticalUpdate: NO\n                                 productType: (null)\n                            autoInstallDelay: 0\n                                 notifyAfter: NO\n                                   sepDigest: (null)\n                               sepTBMDigests: (null)\n                                  rsepDigest: (null)\n                              rsepTBMDigests: (null)\n            documentationReleaseNotesSummary: {length = 4872, bytes = 0x3c21444f 43545950 45206874 6d6c2050 ... 3c2f6874 6d6c3e0a }\n                   documentationReleaseNotes: (null)\n               documentationLicenseAgreement: (null)\n documentationHumanReadableDocumentationName: macOS Monterey 12.1\n                     documentationSLAVersion: 1775\n                       documentationLanguage: en-US\n                                sfrAssetType: (null)\n                           sfrProductVersion: (null)\n                      sfrProductBuildVersion: (null)\n                              sfrReleaseType: (null)\n                           sfrRestoreVersion: (null)\n                        sfrPrerequisiteBuild: (null)\n                      sfrPrerequisiteVersion: (null)\n                          sfrFullReplacement: NO\n                         sfrSupportedDevices: (null)\n                             sfrDownloadSize: 0\n                           sfrUnarchivedSize: 0\n                           sfrMSUPrepareSize: 0\n                          sfrPreparationSize: 0\n                         sfrInstallationSize: 0\n               sfrMinimumSystemPartitionSize: 0\n                   sfrTotalRequiredFreeSpace: 0\n                        updateBrainAssetType: com.apple.MobileAsset.MobileSoftwareUpdate.MacUpdateBrain\n             updateBrainCompatibilityVersion: 20\n                     updateBrainBuildVersion: 21C52\n                        associatedDescriptor: macOS Monterey 12.1 21C52 (Customer)\n                        primarySFRDescriptor: (null)\n                      secondarySFRDescriptor: (null)\n                       updateBrainDescriptor: iOS 12.1 21C52 (Customer)\n                 shouldPerformBridgeOSUpdate: NO\n                    bridgeOSVersionToInstall: (null)\n                   bridgeOSDownloadSizeBytes: (null)\n                   bridgeOSDownloadDirectory: (null)\n                  shouldPerformRosettaUpdate: NO\n                     rosettaVersionToInstall: (null)\n                    rosettaPackageSpecifiers: (null)\n                      recoveryOSUpdateResult: NO\n                    recoveryOSUpdateRequired: NO\n                       recoveryOSUpdateError: (null)\n                  recoveryOSUpdateAttributes: (null)\n<<<]"
	)
2022-01-19 12:52:38-06 SNSNSNSNSNSN softwareupdated[299]: SUOSUServiceDaemon: Queued overrides up for postlogout: (null)
```

**Comment by Lotusshaney** [comment]
So maybe the best work around wound be an option to make the Intel Apple Updates work in the same was as the M1 updates and defer all updates to the Pref Pane ?  Also gives a constant UI experience regardless of architecture?

**Comment by gregneagle** [comment]
That may end up being the route to take. It will mean that Munki will make no attempt to install any Apple software updates. Currently on Intel it does install non-OS updates.
If we go that route, the next obvious step might be to remove all support for Apple software updates from Munki, since it's not really doing anything useful other than notifications, which could be handled by Apple's native mechanisms.

**Comment by gregneagle** [comment]
You can get to that endgame today with no code changes by setting InstallAppleSoftwareUpdates to False.

**Comment by Lotusshaney** [comment]
Hi Greg, I think you should keep Munki showing Apple Updates and using the Pref Pane for the install.  Users have only one place to go to see all updates, so that's great from a UI/UX point, but also Munki showing the Apple Updates is a great way to get end users to install them without having to use another product like nudge.

Ive found users ignore most of the OS notifications but having Munki display a window that shows the Apple updates is more effective.

Please don't remove support for Apple updates, its one of the key reasons Munki is such a power tool.

**Comment by vmiller** [comment]
On the same iMac16,2 - wiped and re-installed to 12.0.1  A commnadline invocation of softwareupdate is successful :

vaughn@Vaughns-iMac ~ % date
Fri Jan 21 07:49:47 EST 2022
vaughn@Vaughns-iMac ~ % sudo softwareupdate -da
Password:
Software Update Tool

Finding available software
Downloading macOS Monterey 12.1
Downloading: 100.00%
Downloaded: macOS Monterey 12.1
vaughn@Vaughns-iMac ~ % date
Fri Jan 21 08:16:02 EST 2022
vaughn@Vaughns-iMac ~ % 

install.log here : https://gist.github.com/vmiller/8baea60348eb26cdf8ad4c606bf02ae3

And as @poundbangbash noticed, the update is then applied upon a reboot.

**Comment by poundbangbash** [comment]
What about a 2nd run of software update after the first successful download?  My expectation is that it would hang at the Downloading phase. 

-Eric

**Comment by vmiller** [comment]
I actually just got done testing the inverse of that...  After killing a hung managedsoftwareupdate auto run, I was able to successfully download the update with softwareupdate -da

I'll try your test next.

**Comment by gregneagle** [comment]
At this point the only thing we know for sure is that for some users/in some orgs, `softwareupdate -da` fails to exit when called by Munki. The issue is not affecting me or my org. Unless we can zero in on the precise trigger/cause, there are two options:

1) Do nothing. Orgs affected by this should disable Munki softwareupdate checking.

2) Change Munki to to no longer download (or install) any Apple softwareupdates on Big Sur+ (though I think some reporters claim to see this problem on macOS < Big Sur). Since this is the behavior currently on Apple silicon, and since Apple silicon deployed percentage will only go up, this seems a reasonable change.

**Comment by gregneagle** [comment]
Even if Munki is completely successful at all times running `softwareupdate -da` I am disturbed by the unexpected install of the OS update at the next reboot. This alone makes me want to stop downloading OS updates at least, regardless of architecture.

**Comment by vmiller** [comment]
For what it's worth, all of my testing is done without any of my org's management (I'm even testing on my home network).   And yes I realize I will likely need to configure munki in my org to no longer check for apple updates.

I wish I could convince my org to get rid of Macs in labs...

**Comment by gregneagle** [comment]
Or get rid of "computer labs", a relic of the 1990s and early 2000s...

**Comment by vmiller** [comment]
That's even less likely to happen :-)

**Comment by vmiller** [comment]
A second run of softwareupdate completes successfully

vaughn@Vaughns-iMac ~ % date
Fri Jan 21 12:40:21 EST 2022
vaughn@Vaughns-iMac ~ % sudo softwareupdate -da
Password:
Software Update Tool

Finding available software
Downloading macOS Monterey 12.1
Downloading: 100.00%
Downloaded: macOS Monterey 12.1
vaughn@Vaughns-iMac ~ % date
Fri Jan 21 13:08:22 EST 2022
vaughn@Vaughns-iMac ~ % sudo softwareupdate -da
Password:
Software Update Tool

Finding available software
Downloading macOS Monterey 12.1

Downloaded: macOS Monterey 12.1
vaughn@Vaughns-iMac ~ % date
Fri Jan 21 13:08:38 EST 2022
vaughn@Vaughns-iMac ~ % 

> What about a 2nd run of software update after the first successful download? My expectation is that it would hang at the Downloading phase.
> […](#)
> -Eric
> On Jan 21, 2022, at 9:23 AM, Vaughn Miller ***@***.***> wrote: ﻿ On the same iMac16,2 - wiped and re-installed to 12.0.1 A commnadline invocation of softwareupdate is successful : ***@***.*** ~ % date Fri Jan 21 07:49:47 EST 2022 ***@***.*** ~ % sudo softwareupdate -da Password: Software Update Tool Finding available software Downloading macOS Monterey 12.1 Downloading: 100.00% Downloaded: macOS Monterey 12.1 ***@***.*** ~ % date Fri Jan 21 08:16:02 EST 2022 ***@***.*** ~ % install.log here : https://gist.github.com/vmiller/8baea60348eb26cdf8ad4c606bf02ae3 And as @poundbangbash noticed, the update is then applied upon a reboot. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

**Comment by poundbangbash** [comment]
The one test machine I saw this behavior with had downloaded the update, but then 20 minutes later the logs show the update was stashed for next reboot install.  It may not be a back to back consecutive run that shows the hang.  It seems the stash has to happen first but I'm not sure if there is a way to trigger that or just let time pass.

**Comment by cfatechsupport** [comment]
Anyone have progress on this issue?  We use Munki to deploy some 3rd party apps, but have all Apple checking/installing turned off in our labs so I'm feeling like it's not Munki related. 

What's Im seeing is strange softwareupdate behaviour in general.  Take a look a these back to back softwareupdate -l runs made just minutes apart:


`
admin@ART-258/ % softwareupdate -l --verbose --all                                                              
Software Update Tool

Finding available software
2022-02-04 16:47:38.215 softwareupdate[1933:10275] XType: com.apple.fonts is not accessible.
2022-02-04 16:47:38.215 softwareupdate[1933:10275] XType: XTFontStaticRegistry is enabled.
No new software available.
admin@ART-258 / % softwareupdate -l --verbose --all
Software Update Tool

Finding available software
2022-02-04 16:48:11.201 softwareupdate[1948:10448] XType: com.apple.fonts is not accessible.
2022-02-04 16:48:11.201 softwareupdate[1948:10448] XType: XTFontStaticRegistry is enabled.
Software Update found the following new or updated software:
* Label: macOS Monterey 12.2-21D49
	Title: macOS Monterey 12.2, Version: 12.2, Size: 1892345K, Recommended: YES, Action: restart, 
admin@ART-258 / % softwareupdate -l --verbose --all
Software Update Tool

Finding available software
2022-02-04 16:48:22.015 softwareupdate[1951:10510] XType: com.apple.fonts is not accessible.
2022-02-04 16:48:22.016 softwareupdate[1951:10510] XType: XTFontStaticRegistry is enabled.
No new software available.
admin@ART-258 / % softwareupdate -l --verbose --all
Software Update Tool

Finding available software
2022-02-04 16:48:32.274 softwareupdate[1954:10557] XType: com.apple.fonts is not accessible.
2022-02-04 16:48:32.275 softwareupdate[1954:10557] XType: XTFontStaticRegistry is enabled.
No new software available.
`

**Comment by Lotusshaney** [comment]
I see this all the time too, all the way back to Catalina.  I think any cli running of softwareupdate in current macOS is troublesome !

**Comment by fuzzylogiq** [comment]
Resolved Issues in macOS 12.3 Beta
(Beta 4) Resolves an issue where software update scans may become unresponsive.

There are also test releases of 11.6.5 and macOS Catalina Security Update, but we don't get release notes for them. I sure hope this fix is backported if it's the same issue.

**Comment by shoopdawoop** [comment]
Thanks, looking forward to macOS 12.3 then.

By now I found a bunch of machines on which the issue was even more dramatic: the failing download is basically preventing `managedsoftwareupdate` from running, thus preventing updates from being installed or even preventing users from applying updates manually (and I thought they were just lazy), as well as preventing postflight scripts from running (and sometimes for months as seen below).


```
Dec 14 2021 10:49:00 +0100     Downloading macOS Monterey 12.1
Dec 14 2021 19:08:20 +0100 ************************************************************
Dec 14 2021 19:08:20 +0100 managedsoftwareupdate launched as pid 31513
Dec 14 2021 19:08:20 +0100 Another instance of managedsoftwareupdate is running as pid 1723.
Dec 14 2021 19:08:20 +0100 pid 31513 exiting.
Dec 14 2021 19:08:20 +0100 ************************************************************
Dec 14 2021 19:08:30 +0100 ************************************************************
Dec 14 2021 19:08:30 +0100 managedsoftwareupdate launched as pid 31529
Dec 14 2021 19:08:30 +0100 Another instance of managedsoftwareupdate is running as pid 1723.
Dec 14 2021 19:08:30 +0100 pid 31529 exiting.
Dec 14 2021 19:08:30 +0100 ************************************************************
Dec 14 2021 19:08:41 +0100 ************************************************************
Dec 14 2021 19:08:41 +0100 managedsoftwareupdate launched as pid 31544
Dec 14 2021 19:08:41 +0100 Another instance of managedsoftwareupdate is running as pid 1723.
Dec 14 2021 19:08:41 +0100 pid 31544 exiting.
Dec 14 2021 19:08:41 +0100 ************************************************************
```


As I do not have the time to dig deeper into this right now, I guess I will be setting `AppleSoftwareUpdatesOnly` to `false` now as suggested.

**Comment by Lotusshaney** [comment]
So maybe we go with using the Apple Silicon way of software updates and use the pref pane on all platforms. 

That way it should be minimal code change for Greg and gives everyone a unified workflow while maintaining Munkis fantastic prompting for Apple Updates rather than have to look at other products such as nudge.

**Comment by cfatechsupport** [comment]
Just wanted to add, we've had `AppleSoftwareUpdatesOnly` set to `false` for many years now, and it does NOT resolve this issue for us as @shoopdawoop suggests.  Though I too believe this is an issue with softwareupdated that's manifesting via Munki, not necessarily a Munki issue.

**Comment by gregneagle** [comment]
AppleSoftwareUpdatesOnly is for a configuration where you use Munki _only_ for Apple Software Updates. It is False by default and I would not expect that to have any bearing on this issue at all.

https://github.com/munki/munki/wiki/Apple-Software-Updates-With-Munki#using-the-munki-tools-only-to-install-apple-software-updates

**Comment by gregneagle** [comment]
Betting @shoopdawoop meant setting `InstallAppleSoftwareUpdates` to false.

**Comment by shoopdawoop** [comment]
He did indeed; sorry for the mixup -> confusion.

**Comment by Lotusshaney** [comment]
Any more thoughts on this ?

**Comment by PeetMcK** [comment]
@gregneagle A big vote for simply disabling installing updates on < Big Sur. I really want my users reminded of all updates via Munki. 

I've been running into this issue at a good clip across multiple orgs. 

> 2. Change Munki to to no longer download (or install) any Apple softwareupdates on Big Sur+ (though I think some reporters claim to see this problem on macOS < Big Sur). Since this is the behavior currently on Apple silicon, and since Apple silicon deployed percentage will only go up, this seems a reasonable change.

**Comment by ofirgalcon** [comment]
+1

**Comment by gregneagle** [comment]
With this commit: https://github.com/munki/munki/commit/3a41be24a792f49047ea71619707b04de95b6c93 Munki no longer attempts to download Apple software update items that require a restart on macOS 10.14 and above. These are the same updates that must be installed manually via the Software Update preferences pane. I'm hoping that this avoids the hanging -- all of the examples were OS updates.

**Comment by cfatechsupport** [comment]
Thanks Greg!  I think this is a positive move, and again I still squarely blame Apple, I see the hangs elsewhere as well, it's just more obviously manifested in MSC .  However, will this still notify users of the availability of a non-downloadable update?  I hope so, or at least an option to do so.

**Comment by gregneagle** [comment]
Yes, notifications are not affected. Munki traditionally (on Intel at least) has downloaded all available updates before presenting them to the user so the user doesn't agree to install them, and then wait for (a possibly long/slow) download. Now users may have to wait.

**Comment by cfatechsupport** [comment]
Damned if ya do, damned if ya don't!  ;-)  Sometimes I long for the good ol' days of easy macOS updates, but I do think this is the better option for where we're at now, at least in our environment.  Thanks again!

**Comment by gregneagle** [comment]
This code is in the Munki 6.0 beta release. I don't know if it will make it into a 5.7.x release.

**Comment by cfatechsupport** [comment]
I've been testing the updated au.py & su_tool.py scripts (using 5.7.3.4444) and so far so good!  Just curious if not merging into 5.7.x is more about compatibility or time/effort?

**Comment by walkintom** [comment]
Just wanted to throw in that I'm now seeing this on Intel Macs going to macOS 12.6. I was tempted to disable Apple Software Update functionality within Munki but we're still a good 80/20 Intel/Silicon so it's still handy having it install things like Safari, etc.
